[build]
  publish = ".next"
  command = "yarn build"

## blog redirect
[[redirects]]
  from = "/blog*"
  to = "https://danblog.netlify.app/blog/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"

## www.danioved.com => danoved.xyz
[[redirects]]
  from = "https://www.danioved.com*"
  to = "https://danoved.xyz/:splat"
  status = 301
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"

## danoved.com => danoved.xyz
[[redirect]]
  from = 'https://danoved.com/*'
  to = 'https://danoved.xyz/:splat'
  status = 301
  force = true