import { Category, PortfolioItemMeta, ProjectType, Role, Tech } from '@/api/types';

export const meta: PortfolioItemMeta = {
  title: 'Voronoi Cellular Zoetrope',
  dateStart: Date.parse('2018-01-23T17:26:42-05:00'),
  draft: false,
  image: './images/zoetrope_featured_image.gif',
  animatedImage: './images/zoetrope_featured.gif',
  showonlyimage: true,
  weight: 3,
  summary: 'A physical animation generated by graphics shaders that loops seamlessly and infinitely',
  links: {
    externalArticle: '/blog/posts/design_for_digital_fabrication/voronoi-cellular-zoetrope/',
    github: null,
    demo: null,
  },
  projectType: ProjectType.gradSchool,
  role: Role.Artist,
  categories: [Category.Installation],
  tech: [Tech.DigitalFab],
};
